### ISSUE TITLE
大佬, 悄悄的告诉你, 字幕可以和视频同时上传, B站前段时间开通了. 

### ISSUE THREAD

**Issue by lionderful** [ame-yu/u2bili#3]
这里不能截图, 具体位置在:
B站网页投稿页面 "标签", "简介",  "定时发布" 点开下面的 " 更多设置 （含声明与权益、视频元素、互动管理等）" ,
 里边有视频元素,  可以在这个页面, 在上传视频的同时上传字幕

很期待你补充这个功能

我刚参照你的代码写了 python 版 playwright 上传字幕功能, 不过只能在审核后的视频页面提交. 稍显繁琐

最后感谢你, 成就满满

**Comment by xiaobaicode6** [comment]
> playwright

老哥如何联系您啊 想交流一下
